### ISSUE TITLE
玩转Docker

### ISSUE THREAD

**Issue by wmenjoy** [wmenjoy/awesome-knowleges#16]
# Docker 是什么

**Comment by wmenjoy** [comment]
# Docker的安装

**Comment by wmenjoy** [comment]
# 如何使用Docker快速部署一个服务

**Comment by wmenjoy** [comment]
# Docker 镜像的保存

**Comment by wmenjoy** [comment]
# 开发基于Docker的应用程序

**Comment by wmenjoy** [comment]
# Docker的网络配置

**Comment by wmenjoy** [comment]
# 管理Docker的数据

**Comment by wmenjoy** [comment]
# 运行Docker

**Comment by wmenjoy** [comment]
## dockerfile 学习

**Comment by wmenjoy** [comment]
# 常见问题
## 1. docker：pull access denied for hello-wrold, repository does not exist or may require 'docker login'.

提示很明显，执行
```
docker login 
docker login -u xxx
docker login -u xxx  host:port #私有Docker Registries
```

**Comment by wmenjoy** [comment]
# Docker 命令学习
## 容器生命周期管理
### run
### start/stop/restart
### kill
### rm
### pause/unpause
### create
### exec
## 容器操作
### ps
### inspect
### top
### attach
### events
### logs
### wait
### export
### port
## 容器rootfs命令
### commit
### cp
### diff
## 镜像仓库
### login
### pull
### push
### search
## 本地镜像管理
###  images
### rmi
### tag
### build
### history
### save
###  load
### import
## info|version
### info
### version

**Comment by wmenjoy** [comment]
# Docker 端口映射

## 参考
1. [Docker端口映射](https://www.cnblogs.com/williamjie/p/9915036.html)

**Comment by wmenjoy** [comment]
# Docker数据卷

## 参考
1. [Docker学习笔记（6）——Docker Volume
]https://www.jianshu.com/p/ef0f24fd0674)

**Comment by wmenjoy** [comment]
# Alpine

## 参考
1. [Alpine Manual](https://yeasy.gitbooks.io/docker_practice/content/cases/os/alpine.html)

**Comment by wmenjoy** [comment]
# Docker的compser



## 参考
1. [Docker入门篇（三）之docker-compose单机编排](https://www.cnblogs.com/linuxk/p/9287129.html)

**Comment by wmenjoy** [comment]
# 镜像安全

1. [全面易用的镜像漏洞检测工具:Trivy](https://cloud.tencent.com/developer/article/1468240)

**Comment by wmenjoy** [comment]
# Docker 基础镜像选型

## 操作系统选型



## 参考
1. [comparison-linux-container-images](http://crunchtools.com/comparison-linux-container-images/)

**Comment by wmenjoy** [comment]
# 其他

## 测试
1. [cis-docker-benchmark](https://github.com/dev-sec/cis-docker-benchmark)

## 资料
1. [crunchtools](http://crunchtools.com/category/article/page/8/)
2. [alibaba Image-syncer](https://github.com/AliyunContainerService/image-syncer)
3. [alibaba Devops](https://github.com/AliyunContainerService/DevOps)
4. [Docker入门一篇足以](https://mp.weixin.qq.com/s/t81enr-ypBxk1K4lYqWZww)
5.[SUSE & Rancher Community](https://community.suse.com/feed)
6.[docker资料](https://dunwu.github.io/linux-tutorial/docker/#%F0%9F%93%96-%E5%86%85%E5%AE%B9)

**Comment by wmenjoy** [comment]
# Docker 日志收集

## 参考
1. [alibaba log-pilot](https://github.com/AliyunContainerService/log-pilot)

**Comment by wmenjoy** [comment]
# Docker Registry

## 同步镜像
1. [同步外网到本地](https://github.com/AliyunContainerService/sync-repo)
2. [不同docker registy之间的同步](https://github.com/AliyunContainerService/image-syncer)
3. 利用harbor的replica功能，可以在不同的docker registy 之间实现同步
4、

**Comment by wmenjoy** [comment]
# dockerd

## configure and run docker

## 参考
1. [Configure and troubleshoot the Docker daemon](https://docs.docker.com/config/daemon/)
2. [dockerd](https://docs.docker.com/engine/reference/commandline/dockerd/)

**Comment by wmenjoy** [comment]
# docker client

## 配置
### 本机其他用户访问docker
```
gpasswd -a $user docker
newgrp docker
```

## 参考
1. [docker client配置](https://www.cnblogs.com/leozhanggg/p/11730189.html)

**Comment by wmenjoy** [comment]
# Docker的镜像制作

## java
1. [spring docker](https://spring.io/guides/topicals/spring-boot-docker/)

**Comment by wmenjoy** [comment]
# Docker 运维
1、批量删除指定镜像
```
docker image list|grep helloworld|awk  '{print $1":"$2}'|sed 's/^/docker image rm /g;' |sh
```
2、docker go 编译java
```
docker run -e GOPROXY=http://192.168.126.18:3001/repository/goproxy/ --rm -v"$PWD":/test -w /test golang go build .
```

**Comment by wmenjoy** [comment]
# Docker Machine

![image](https://user-images.githubusercontent.com/9961069/87373233-e208b880-c5bb-11ea-9937-c5cb21e20bf0.png)

**Comment by wmenjoy** [comment]
# Docker 导出
```
# 列出
docker images
# 导出
docker save eb40dcf64078> /root/mydjango-save-1016.tar 
## 导入
docker load <  /root/mydjango-save-1016.tar 
docker tag eb40dcf64078 django:latest 
```

**Comment by wmenjoy** [comment]
# 问题排查
## docker 长虹器失败
1. [记一次错误的docker问题排查过程](https://www.jianshu.com/p/4ce0412b50c3)
1. [kernel crash after "unregister_netdevice: waiting for lo to become free. Usage count = 3" #5618
](https://github.com/moby/moby/issues/5618)
1. [unregister_netdevice: waiting for eth0 to become free. Usage count = 1](https://lore.kernel.org/lkml/CAM_iQpWMWg5ytDq2Y9p9uet1zowGuCX+eksyiyxu9vQ18WoPxQ@mail.gmail.com/T/)
1. [](

**Comment by wmenjoy** [comment]
# 僵尸进程

## 参考

1. [Docker和孤儿进程、僵尸进程](https://blog.csdn.net/weixin_34378969/article/details/90587579)
2. [构建容器的最贱实践](https://cloud.google.com/solutions/best-practices-for-building-containers#signal-handling)

**Comment by wmenjoy** [comment]
# 时区修改

1.  操作系统修改时区
    ```bash
     # 1、CentOS6、Ubuntu16
      cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
     
     # 2、CentOS7、RHEL7、Scientific Linux 7、Oracle Linux 7 最好的方法是使用timedatectl命令
     timedatectl list-timezones |grep Shanghai    #查找中国时区的完整名称
     Asia/Shanghai
     timedatectl set-timezone Asia/Shanghai    #其他时区以此类推

      # 3、直接手动创建软链接
      ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
     ```

如果不生效，还需要安装tzdate




## 参考
1. [Docker时间不一致，时区设置](https://blog.csdn.net/catoop/article/details/89737861)
1. [How to Change Timezone on Ubuntu 18.04 & 16.04 LTS](https://tecadmin.net/change-timezone-on-ubuntu/)
1. [dockerfile解决docker ubuntu16.04 时区问题](https://www.jianshu.com/p/12e852c5b7d3)

**Comment by wmenjoy** [comment]
# Docker  Registy  清理

## 清理策略
1、 根据创建时间来清理
2、根据是否使用的时间
3、每一个docker image 保留固定的版本

**Comment by wmenjoy** [comment]
# Nexus3 db修复
## 问题
nexus3 磁盘空间满后 docker 启动报"cannot open local storage '/nexus-data/db/config' with mode=rw"


```java
java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3706)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4413)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:581)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:316)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
        at org.sonatype.nexus.orient.DatabaseManagerSupport.connect(DatabaseManagerSupport.java:178)
        at org.sonatype.nexus.orient.DatabaseManagerSupport.createInstance(DatabaseManagerSupport.java:312)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.sonatype.nexus.orient.DatabaseManagerSupport.instance(DatabaseManagerSupport.java:289)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2020-11-19 01:57:31,172+0000 ERROR [ForkJoinPool.commonPool-worker-1] *SYSTEM com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage - Exception `47820D6D` in storage `plocal:/nexus-data/db/config`: 2.2.36 (build d3beb772c02098ceaea89779a7afd4b7305d3788, branch 2.2.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/nexus-data/db/config' with mode=rw^M
        DB name="config"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:323)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
        at org.sonatype.nexus.orient.DatabaseManagerSupport.connect(DatabaseManagerSupport.java:178)
        at org.sonatype.nexus.orient.DatabaseManagerSupport.createInstance(DatabaseManagerSupport.java:312)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.sonatype.nexus.orient.DatabaseManagerSupport.instance(DatabaseManagerSupport.java:289)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3706)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:3937)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:288)
        ... 14 common frames omitted
```

**Comment by wmenjoy** [comment]
# Nexus_Cli

## 文档
1. [Thiago Figueiró / docker-nexus3-cli · GitLab](https://gitlab.com/thiagocsf/docker-nexus3-cli)
2. [nexus3-cli · PyPI](https://pypi.org/project/nexus3-cli/)
3. [nexus3-casc-cli/Dockerfile at master · vjda/nexus3-casc-cli](https://github.com/vjda/nexus3-casc-cli/blob/master/Dockerfile)
4. [Thiago Figueiró / Nexus 3 CLI · GitLab](https://gitlab.com/thiagocsf/nexus3-cli)

**Comment by wmenjoy** [comment]
## 镜像的连线制作

## 操作系统相关资源
### centos
1. [CentOS Mirror](http://mirror.centos.org/centos/7/os/x86_64/Packages/)

**Comment by wmenjoy** [comment]
# 最佳实践

1. [Top 20 Dockerfile best practices for security | Sysdig](https://sysdig.com/blog/dockerfile-best-practices/)

**Comment by wmenjoy** [comment]
# Docker的替代品
1. [Beyond Docker: A Look at Alternatives to Container Management | SUSE & Rancher Community](https://community.suse.com/posts/beyond-docker-a-look-at-alternatives-to-container-management-14411837)

**Comment by wmenjoy** [comment]
# 镜像简化
1. [docker-slim/docker-slim: DockerSlim (docker-slim): Don't change anything in your Docker container image and minify it by up to 30x (and for compiled languages even more) making it secure too! (free and open source)](https://github.com/docker-slim/docker-slim)

**Comment by wmenjoy** [comment]
# 镜像与集群
1. [ContainerSolutions/ImageWolf: Fast Distribution of Docker Images on Clusters](https://github.com/ContainerSolutions/ImageWolf)
